gesdinet_jwt_refresh_token:
  refresh_token_class: Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken
  object_manager: doctrine.orm.entity_manager
  refresh_token_parameter_name: refresh_token
  ttl: 2592000
  firewall: main
  user_provider: security.user.provider.concrete.app_user_provider
