nelmio_api_doc:
    documentation:
        info:
            title: 'API ProjetPro'
            description: |
                API REST pour l'application ProjetPro avec système d'authentification sécurisé.

                ## Fonctionnalités principales:
                - Authentification avec protection anti-force brute
                - Gestion des tokens CSRF
                - Upload d'images vers Azure Blob Storage
                - Logging automatique des tentatives de connexion
                - Système de blocage par IP et par login

                ## Sécurité:
                - Protection CSRF obligatoire
                - Tokens d'authentification JWT
                - Blocage automatique après échecs répétés

                ## Headers requis:
                - `X-CSRF-Token`: Token CSRF pour les requêtes POST
                - `Authorization: Bearer <token>`: Token JWT pour l'authentification
                - `Content-Type: application/json`
            version: '1.0.0'
            contact:
                name: 'Support API'
                email: 'support@projetpro.com'
        servers:
            - url: 'http://localhost:8000'
              description: 'Serveur de développement'
            - url: '/api'
              description: 'API Production'
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    description: 'Token JWT d''authentification'
                csrfToken:
                    type: apiKey
                    in: header
                    name: X-CSRF-Token
                    description: 'Token CSRF pour la protection contre les attaques CSRF'
        security:
            - bearerAuth: []
            - csrfToken: []
        tags:
            - name: 'Authentication'
              description: 'Gestion de l''authentification utilisateur'
            - name: 'CSRF Token'
              description: 'Gestion des tokens CSRF'
            - name: 'JWT Tokens'
              description: 'Gestion des tokens JWT (refresh, validation, révocation)'
            - name: 'Images'
              description: 'Gestion des images via Azure Blob Storage'
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    models:
        use_jms: false
