nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: true
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_origin: ['*']
        allow_methods: ['GET','OPTIONS','POST','PUT','PATCH','DELETE']
        allow_headers: ['Content-Type','Authorization','X-Requested-With','X-CSRF-TOKEN']
        max_age: 3600

    paths:
        '^/api/.*':
            origin_regex: true
            allow_credentials: true
            # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_origin: ['*']
            allow_methods: ['GET','OPTIONS','POST','PUT','PATCH','DELETE']
            allow_headers: ['Content-Type','Authorization','X-Requested-With','X-CSRF-TOKEN']
            max_age: 3600