apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: local
data:
  GF_SERVER_HTTP_PORT: "3000"
  GF_SERVER_DOMAIN: "grafana.muscuscope.local"
  GF_SERVER_ROOT_URL: "https://grafana.muscuscope.local"
  GF_SECURITY_ALLOW_EMBEDDING: "true"
  GF_AUTH_ANONYMOUS_ENABLED: "false"
  GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
  GF_DATABASE_TYPE: "postgres"
  GF_DATABASE_HOST: "postgres-postgres.infra.svc.cluster.local:5432"
  GF_DATABASE_NAME: "grafana"
  GF_DATABASE_SSL_MODE: "disable"
