apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: local
type: Opaque
data:
  # Base64 encoded values - À remplacer par vos vraies valeurs
  GF_SECURITY_ADMIN_USER: YWRtaW4=  # admin
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=  # admin - À CHANGER EN PRODUCTION !
  GF_DATABASE_USER: Z3JhZmFuYQ==  # grafana
  GF_DATABASE_PASSWORD: Z3JhZmFuYQ==  # grafana
  GF_SECURITY_SECRET_KEY: Z3JhZmFuYS1zZWNyZXQta2V5LWZvci1zaWduaW5n  # grafana-secret-key-for-signing
