controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# JWT Authentication routes
api_login_check:
    path: /api/login_check
    methods: [ POST ]

# JWT refresh token route
gesdinet_jwt_refresh_token:
    resource: "@GesdinetJWTRefreshTokenBundle/Resources/config/routing.yaml"
    prefix: /api
