services:
  backend:
    image: backend:latest
    build:
      context: ./web
    volumes:
      - $APP_DIR:/var/www/app
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - $APP_PORT:80
      - 8000:8000
    networks:
      - projetProNetcwork

  bdd:
    image: postgres:15.8-bookworm
    environment:
      POSTGRES_DB: projetPro
      POSTGRES_USER: projetPro
      POSTGRES_PASSWORD: projetPro
    ports:
      - $BDD_PORT:5432
    volumes:
      - $BDD_DIR:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - projetProNetcwork

  grafana:
    image: grafana/grafana-oss:12.0.2-ubuntu
    ports:
      - 3000:3000
    networks:
      - projetProNetcwork

networks:
  projetProNetcwork:
    name: projetProNetcwork
    external: true
