apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: muscuscope/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_API_URL
        - name: VITE_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_APP_NAME
        - name: VITE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_ENVIRONMENT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10