apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: local
type: Opaque
data:
  # Base64 encoded values - À remplacer par vos vraies valeurs
  DATABASE_USER: cHJvamV0UHJv  # projetPro
  DATABASE_PASSWORD: cHJvamV0UHJv  # projetPro
  JWT_SECRET: bXVzY3VzY29wZS1qd3Qtc2VjcmV0LWtleQ==  # muscuscope-jwt-secret-key
  AZURE_STORAGE_CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPW11c2N1c2NvcGU7QWNjb3VudEtleT15b3VyLWFjY291bnQta2V5  # À remplacer